services:
  activemq:
    image: rmohr/activemq:5.16.7
    container_name: activemq-broker
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - activemq-data:/opt/activemq/data
    restart: unless-stopped

volumes:
  activemq-data: